CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR UNIQUE NOT NULL,
    description TEXT,
    min_price DECIMAL(10, 2),
    max_price DECIMAL(10, 2)
);

CREATE TABLE IF NOT EXISTS forbidden_names (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR UNIQUE NOT NULL,
    reason TEXT
);

CREATE TABLE IF NOT EXISTS products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    price DECIMAL(10, 2),
    count INTEGER,
    description TEXT,
    category_id INTEGER REFERENCES categories(id)
);

CREATE TABLE IF NOT EXISTS products_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL,
    action VARCHAR NOT NULL,
    previous_state JSONB NOT NULL,
    current_state JSONB NOT NULL,
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_products_history_product_id 
    ON products_history(product_id);

INSERT INTO categories (name, description, min_price, max_price)
VALUES
    ('Computers', 'Laptops and desktops', 500.00, 3000.00),
    ('Accessories', 'Peripheral devices', 5.00, 200.00),
    ('Keyboards', 'Keyboard devices', 20.00, 300.00);

INSERT INTO forbidden_names (name, reason)
VALUES
    ('Test', 'Reserved for testing'),
    ('Unknown', 'Ambiguous name'),
    ('N/A', 'Not a valid product name');

INSERT INTO products (name, price, count, description, category_id)
VALUES
    ('Laptop', 1500.00, 10, 'High-performance laptop', 1),
    ('Mouse', 29.99, 50, 'Wireless mouse', 2),
    ('Keyboard', 79.99, 30, 'Mechanical keyboard', 3),
    ('Gaming Laptop', 2500.00, 5, 'High-end gaming laptop', 1),
    ('USB-C Hub', 49.99, 20, 'Multi-port USB-C hub', 2),
    ('Ergonomic Keyboard', 129.99, 15, 'Ergonomic design keyboard', 3),
    ('Desktop PC', 1200.00, 8, 'Powerful desktop computer', 1),
    ('Monitor', 299.99, 12, '4K monitor', 2),
    ('Mechanical Switch Set', 35.00, 40, 'Replacement switch set', 3),
    ('Laptop Stand', 45.00, 25, 'Adjustable aluminum stand', 2),
    ('Wireless Charger', 39.99, 18, 'Fast wireless charging pad', 2),
    ('Gaming Mouse Pad', 24.99, 35, 'Large gaming mouse pad', 2),
    ('Portable SSD', 89.99, 22, '1TB portable solid state drive', 2),
    ('Laptop Cooling Pad', 55.00, 14, 'Active cooling pad', 2),
    ('Mechanical Keyboard RGB', 159.99, 10, 'RGB backlit mechanical keyboard', 3),
    ('USB Hub', 19.99, 45, '4-port USB 3.0 hub', 2);
