CREATE TABLE IF NOT EXISTS assignment_drafts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id INTEGER NOT NULL REFERENCES operators(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS assignment_draft_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draft_id INTEGER NOT NULL REFERENCES assignment_drafts(id) ON DELETE CASCADE,
    student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_assignment_draft_student UNIQUE (draft_id, student_id)
);

CREATE TABLE IF NOT EXISTS assignment_batches (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id INTEGER NOT NULL REFERENCES operators(id) ON DELETE CASCADE,
    assignment_number VARCHAR NOT NULL UNIQUE,
    status VARCHAR NOT NULL DEFAULT 'PENDING',
    students_count INTEGER NOT NULL DEFAULT 0,
    total_ects INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS assignment_batch_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id INTEGER NOT NULL REFERENCES assignment_batches(id) ON DELETE CASCADE,
    student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE RESTRICT,
    student_name VARCHAR NOT NULL,
    student_lastname VARCHAR NOT NULL,
    student_code VARCHAR NOT NULL,
    ects_points INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_assignment_drafts_operator_id
    ON assignment_drafts(operator_id);

CREATE INDEX IF NOT EXISTS idx_assignment_draft_items_draft_id
    ON assignment_draft_items(draft_id);

CREATE INDEX IF NOT EXISTS idx_assignment_batches_operator_id
    ON assignment_batches(operator_id);

CREATE INDEX IF NOT EXISTS idx_assignment_batch_items_batch_id
    ON assignment_batch_items(batch_id);