CREATE TABLE IF NOT EXISTS processed_commands (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    command_name VARCHAR NOT NULL,
    idempotency_key VARCHAR NOT NULL,
    operator_id INTEGER NOT NULL REFERENCES operators(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_processed_command_key UNIQUE (command_name, idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_processed_commands_operator_id
    ON processed_commands(operator_id);